import { queryOptions } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import type { Tables } from "@/integrations/supabase/types";

export type Product = Tables<"products"> & {
  categorySlug: string;
  category?: string;
  image?: string;
  title?: string;
};
export type Category = Tables<"categories">;
export type Review = Tables<"reviews">;
export type Order = Tables<"orders">;
export type OrderItem = Tables<"order_items">;
export type Address = Tables<"addresses">;
export type Enquiry = Tables<"enquiries">;

export function normalizeCategorySlug(s: string | undefined | null): string {
  if (!s) return "";
  const cleaned = s
    .toLowerCase()
    .trim()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

  if (cleaned === "3d-printing" || cleaned === "3d-print" || cleaned === "3dprinting") {
    return "3d-printing";
  }
  if (cleaned === "laser-cutting" || cleaned === "laser-cut" || cleaned === "lasercutting") {
    return "laser-cutting";
  }
  if (cleaned === "cnc-machining" || cleaned === "cnc" || cleaned === "cncmachining") {
    return "cnc-machining";
  }
  if (cleaned === "electronics" || cleaned === "electronic") {
    return "electronics";
  }
  if (
    cleaned === "drones-parts" ||
    cleaned === "drones-and-parts" ||
    cleaned === "drones" ||
    cleaned === "drone-parts"
  ) {
    return "drones-parts";
  }
  if (cleaned === "acrylic-products" || cleaned === "acrylic" || cleaned === "acrylics") {
    return "acrylic-products";
  }
  if (cleaned === "diy-kits" || cleaned === "diy" || cleaned === "kits") {
    return "diy-kits";
  }

  return cleaned;
}

export const EXACT_PRODUCT_CATEGORY_MAP: Record<string, string> = {
  "3d-printed-geometric-spiral-vase": "3d-printing",
  "foldable-desktop-phone-tablet-stand": "3d-printing",
  "modular-desktop-stationery-organizer": "3d-printing",
  "interlocking-cable-management-clip-pack": "3d-printing",
  "precision-resin-architectural-tower-model": "3d-printing",
  "hexagonal-geometric-succulent-planter-pot": "3d-printing",
  "custom-laser-engraved-wooden-keychain": "laser-cutting",
  "laser-cut-tree-of-life-wooden-led-lamp": "laser-cutting",
  "slot-together-plywood-desktop-organizer": "laser-cutting",
  "multi-layered-wooden-mandala-wall-art": "laser-cutting",
  "laser-engraved-hardwood-photo-frame": "laser-cutting",
  "edge-lit-laser-cut-acrylic-led-sign": "laser-cutting",
  "cnc-v-carved-solid-walnut-name-plate": "cnc-machining",
  "cnc-relief-carved-wooden-decorative-panel": "cnc-machining",
  "cnc-milled-hardwood-keepsake-box": "cnc-machining",
  "cnc-machined-6061-aluminium-l-bracket": "cnc-machining",
  "cnc-precision-aluminium-fixture-plate": "cnc-machining",
  "cnc-machined-high-precision-spur-gear": "cnc-machining",
  "esp32-dual-core-iot-development-board": "electronics",
  "37-piece-iot-sensor-module-starter-kit": "electronics",
  "double-sided-fr4-prototype-pcb-pack": "electronics",
  "arduino-compatible-atmega328p-microcontroller": "electronics",
  "i2c-096-inch-oled-display-module": "electronics",
  "5-inch-fpv-racing-3k-carbon-fiber-drone-frame": "drones-parts",
  "2207-2450kv-high-power-brushless-drone-motor": "drones-parts",
  "5-inch-tri-blade-fpv-drone-propellers-pack": "drones-parts",
  "30a-4-in-1-blheli-s-electronic-speed-controller": "drones-parts",
  "omnidirectional-58ghz-fpv-cloverleaf-antenna": "drones-parts",
  "crystal-clear-cast-acrylic-showcase-cube-box": "acrylic-products",
  "laser-engraved-beveled-acrylic-award-trophy": "acrylic-products",
  "high-clarity-heavy-duty-acrylic-sneeze-shield": "acrylic-products",
  "desktop-acrylic-slanted-brochure-menu-holder": "acrylic-products",
  "multi-tiered-clear-acrylic-cosmetic-display-riser": "acrylic-products",
  "autonomous-4wd-smart-robotic-stem-starter-kit": "diy-kits",
  "educational-electronics-soldering-practice-kit": "diy-kits",
  "diy-portable-bluetooth-stereo-speaker-maker-kit": "diy-kits",
  "miniature-solar-powered-stem-rover-buggy-kit": "diy-kits",
  "smart-weather-station-iot-esp8266-maker-kit": "diy-kits",
};

export const categoriesQuery = queryOptions({
  queryKey: ["categories"],
  queryFn: async (): Promise<Category[]> => {
    const { data, error } = await supabase.from("categories").select("*").order("sort_order");
    if (error) throw error;
    return data ?? [];
  },
  staleTime: 5 * 60_000,
});

export const DEFAULT_CATALOG_PRODUCTS: Product[] = [
  {
    id: "3dp-001",
    name: "3D Printed Geometric Spiral Vase",
    title: "3D Printed Geometric Spiral Vase",
    slug: "3d-printed-geometric-spiral-vase",
    category: "3D Printing",
    categorySlug: "3d-printing",
    price: 649,
    original_price: 899,
    discount: 28,
    rating: 4.9,
    reviews_count: 38,
    stock: 24,
    description: "Parametric twisted spiral vase 3D printed in silk rainbow gradient PLA with subtle layer lines and watertight inner geometry.",
    image: "/products/v4/3d-printed-geometric-spiral-vase.jpg",
    image_key: "3d-printed-geometric-spiral-vase",
    tags: ["3d-printing", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "3dp-002",
    name: "3D Printed Foldable Phone Stand",
    title: "3D Printed Foldable Phone Stand",
    slug: "3d-printed-foldable-phone-stand",
    category: "3D Printing",
    categorySlug: "3d-printing",
    price: 349,
    original_price: 499,
    discount: 30,
    rating: 4.8,
    reviews_count: 52,
    stock: 45,
    description: "Print-in-place multi-angle folding smartphone and tablet stand with ratcheting support arms in vibrant matte orange PETG.",
    image: "/products/v4/3d-printed-foldable-phone-stand.jpg",
    image_key: "3d-printed-foldable-phone-stand",
    tags: ["3d-printing", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "3dp-003",
    name: "3D Printed Mini Desk Organizer",
    title: "3D Printed Mini Desk Organizer",
    slug: "3d-printed-mini-desk-organizer",
    category: "3D Printing",
    categorySlug: "3d-printing",
    price: 499,
    original_price: 699,
    discount: 29,
    rating: 4.7,
    reviews_count: 29,
    stock: 30,
    description: "Compact interlocking desktop organizer caddy with dedicated pen cylinders, card slots, and SD card holders in dual-tone teal and charcoal.",
    image: "/products/v4/3d-printed-mini-desk-organizer.jpg",
    image_key: "3d-printed-mini-desk-organizer",
    tags: ["3d-printing", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "3dp-004",
    name: "3D Printed Cable Management Clips Pack",
    title: "3D Printed Cable Management Clips Pack",
    slug: "3d-printed-cable-management-clips-pack",
    category: "3D Printing",
    categorySlug: "3d-printing",
    price: 299,
    original_price: 449,
    discount: 33,
    rating: 4.9,
    reviews_count: 64,
    stock: 80,
    description: "Set of 8 snap-fit interlocking cable management routing clips in assorted neon colors with adhesive mounting channels.",
    image: "/products/v4/3d-printed-cable-management-clips-pack.jpg",
    image_key: "3d-printed-cable-management-clips-pack",
    tags: ["3d-printing", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "3dp-005",
    name: "3D Printed Resin Architectural Tower Model",
    title: "3D Printed Resin Architectural Tower Model",
    slug: "3d-printed-resin-architectural-tower-model",
    category: "3D Printing",
    categorySlug: "3d-printing",
    price: 1299,
    original_price: 1799,
    discount: 28,
    rating: 5.0,
    reviews_count: 19,
    stock: 12,
    description: "High-precision 8K SLA photopolymer resin architectural skyscraper miniature with translucent micro-facades and delicate cantilever decks.",
    image: "/products/v4/3d-printed-resin-architectural-tower-model.jpg",
    image_key: "3d-printed-resin-architectural-tower-model",
    tags: ["3d-printing", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "3dp-006",
    name: "3D Printed Hexagonal Geometric Succulent Planter",
    title: "3D Printed Hexagonal Geometric Succulent Planter",
    slug: "3d-printed-hexagonal-geometric-succulent-planter",
    category: "3D Printing",
    categorySlug: "3d-printing",
    price: 399,
    original_price: 599,
    discount: 33,
    rating: 4.8,
    reviews_count: 41,
    stock: 35,
    description: "Geometric low-poly hexagonal succulent pot printed in terracotta PLA with built-in drainage holes and matching drip saucer.",
    image: "/products/v4/3d-printed-hexagonal-geometric-succulent-planter.jpg",
    image_key: "3d-printed-hexagonal-geometric-succulent-planter",
    tags: ["3d-printing", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "3dp-007",
    name: "3D Printed Modular Tool Holder",
    title: "3D Printed Modular Tool Holder",
    slug: "3d-printed-modular-tool-holder",
    category: "3D Printing",
    categorySlug: "3d-printing",
    price: 549,
    original_price: 799,
    discount: 31,
    rating: 4.8,
    reviews_count: 23,
    stock: 28,
    description: "Gridfinity-compatible honeycomb modular workbench tool holder for hex keys, calipers, pliers, and tweezers in industrial electric blue PETG.",
    image: "/products/v4/3d-printed-modular-tool-holder.jpg",
    image_key: "3d-printed-modular-tool-holder",
    tags: ["3d-printing", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "3dp-008",
    name: "3D Printed Articulated Dragon",
    title: "3D Printed Articulated Dragon",
    slug: "3d-printed-articulated-dragon",
    category: "3D Printing",
    categorySlug: "3d-printing",
    price: 899,
    original_price: 1299,
    discount: 31,
    rating: 5.0,
    reviews_count: 77,
    stock: 18,
    description: "Flexible print-in-place articulated mythical dragon printed in dual-extrusion silk metallic emerald and gold with posable ball joints.",
    image: "/products/v4/3d-printed-articulated-dragon.jpg",
    image_key: "3d-printed-articulated-dragon",
    tags: ["3d-printing", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "3dp-009",
    name: "3D Printed Mechanical Gear Assembly",
    title: "3D Printed Mechanical Gear Assembly",
    slug: "3d-printed-mechanical-gear-assembly",
    category: "3D Printing",
    categorySlug: "3d-printing",
    price: 749,
    original_price: 1049,
    discount: 29,
    rating: 4.9,
    reviews_count: 31,
    stock: 16,
    description: "Educational planetary gearbox demonstrator with functioning sun, planet, and ring gears with smooth crank in dual-tone ruby and silver.",
    image: "/products/v4/3d-printed-mechanical-gear-assembly.jpg",
    image_key: "3d-printed-mechanical-gear-assembly",
    tags: ["3d-printing", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "3dp-010",
    name: "3D Printed Headphone Stand",
    title: "3D Printed Headphone Stand",
    slug: "3d-printed-headphone-stand",
    category: "3D Printing",
    categorySlug: "3d-printing",
    price: 799,
    original_price: 1199,
    discount: 33,
    rating: 4.8,
    reviews_count: 46,
    stock: 22,
    description: "Sculptural curved desktop headphone rest with weighted base and integrated cable spool in matte jet-black and crimson accent PLA.",
    image: "/products/v4/3d-printed-headphone-stand.jpg",
    image_key: "3d-printed-headphone-stand",
    tags: ["3d-printing", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "3dp-011",
    name: "3D Printed Desk Cable Dock",
    title: "3D Printed Desk Cable Dock",
    slug: "3d-printed-desk-cable-dock",
    category: "3D Printing",
    categorySlug: "3d-printing",
    price: 449,
    original_price: 649,
    discount: 31,
    rating: 4.7,
    reviews_count: 25,
    stock: 34,
    description: "Weighted desktop charging cable anchor dock with silicone friction pads and 5 magnetic cable collar slots in cyber yellow PETG.",
    image: "/products/v4/3d-printed-desk-cable-dock.jpg",
    image_key: "3d-printed-desk-cable-dock",
    tags: ["3d-printing", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "3dp-012",
    name: "3D Printed Parametric Wall Planter",
    title: "3D Printed Parametric Wall Planter",
    slug: "3d-printed-parametric-wall-planter",
    category: "3D Printing",
    categorySlug: "3d-printing",
    price: 599,
    original_price: 849,
    discount: 29,
    rating: 4.9,
    reviews_count: 33,
    stock: 20,
    description: "Wave-faceted geometric wall-mounted indoor planter vessel with concealed keyhole screw mounts printed in pastel sage green PLA.",
    image: "/products/v4/3d-printed-parametric-wall-planter.jpg",
    image_key: "3d-printed-parametric-wall-planter",
    tags: ["3d-printing", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "lc-001",
    name: "Custom Laser Engraved Wooden Keychain",
    title: "Custom Laser Engraved Wooden Keychain",
    slug: "custom-laser-engraved-wooden-keychain",
    category: "Laser Cutting",
    categorySlug: "laser-cutting",
    price: 199,
    original_price: 299,
    discount: 33,
    rating: 4.9,
    reviews_count: 95,
    stock: 100,
    description: "Precision laser-cut 4mm birch plywood geometric keychain with deep dark burnt engraving and polished steel split ring.",
    image: "/products/v4/custom-laser-engraved-wooden-keychain.jpg",
    image_key: "custom-laser-engraved-wooden-keychain",
    tags: ["laser-cutting", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "lc-002",
    name: "Laser Cut Tree of Life Wooden LED Lamp",
    title: "Laser Cut Tree of Life Wooden LED Lamp",
    slug: "laser-cut-tree-of-life-wooden-led-lamp",
    category: "Laser Cutting",
    categorySlug: "laser-cutting",
    price: 1199,
    original_price: 1699,
    discount: 29,
    rating: 5.0,
    reviews_count: 68,
    stock: 25,
    description: "Circular laser-cut Tree of Life silhouette wooden accent lamp illuminated with built-in warm amber LED glow and solid walnut base.",
    image: "/products/v4/laser-cut-tree-of-life-wooden-led-lamp.jpg",
    image_key: "laser-cut-tree-of-life-wooden-led-lamp",
    tags: ["laser-cutting", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "lc-003",
    name: "Slot-Together Plywood Desktop Organizer",
    title: "Slot-Together Plywood Desktop Organizer",
    slug: "slot-together-plywood-desktop-organizer",
    category: "Laser Cutting",
    categorySlug: "laser-cutting",
    price: 799,
    original_price: 1149,
    discount: 30,
    rating: 4.8,
    reviews_count: 42,
    stock: 30,
    description: "Flat-pack interlocking slot-and-tab laser-cut birch desktop caddy with document trays, pen cups, and precision burnt edges.",
    image: "/products/v4/slot-together-plywood-desktop-organizer.jpg",
    image_key: "slot-together-plywood-desktop-organizer",
    tags: ["laser-cutting", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "lc-004",
    name: "Multi-Layered Wooden Mandala Wall Art",
    title: "Multi-Layered Wooden Mandala Wall Art",
    slug: "multi-layered-wooden-mandala-wall-art",
    category: "Laser Cutting",
    categorySlug: "laser-cutting",
    price: 1499,
    original_price: 2199,
    discount: 32,
    rating: 5.0,
    reviews_count: 54,
    stock: 15,
    description: "8-layer precision laser-cut birch and mahogany layered mandala wall sculpture featuring rich geometric depth and organic drop shadows.",
    image: "/products/v4/multi-layered-wooden-mandala-wall-art.jpg",
    image_key: "multi-layered-wooden-mandala-wall-art",
    tags: ["laser-cutting", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "lc-005",
    name: "Laser Engraved Hardwood Photo Frame",
    title: "Laser Engraved Hardwood Photo Frame",
    slug: "laser-engraved-hardwood-photo-frame",
    category: "Laser Cutting",
    categorySlug: "laser-cutting",
    price: 649,
    original_price: 899,
    discount: 28,
    rating: 4.9,
    reviews_count: 37,
    stock: 40,
    description: "Solid American walnut 4x6 picture frame with intricate laser-etched floral and Celtic filigree borders with glass insert.",
    image: "/products/v4/laser-engraved-hardwood-photo-frame.jpg",
    image_key: "laser-engraved-hardwood-photo-frame",
    tags: ["laser-cutting", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "lc-006",
    name: "Edge-Lit Laser Cut Acrylic LED Sign",
    title: "Edge-Lit Laser Cut Acrylic LED Sign",
    slug: "edge-lit-laser-cut-acrylic-led-sign",
    category: "Laser Cutting",
    categorySlug: "laser-cutting",
    price: 999,
    original_price: 1399,
    discount: 29,
    rating: 4.9,
    reviews_count: 60,
    stock: 25,
    description: "Laser-etched optical clear acrylic panel with vivid cyan LED edge lighting slotted into a rich natural wood illuminated base.",
    image: "/products/v4/edge-lit-laser-cut-acrylic-led-sign.jpg",
    image_key: "edge-lit-laser-cut-acrylic-led-sign",
    tags: ["laser-cutting", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "lc-007",
    name: "Laser Cut Wooden Desk Name Plate",
    title: "Laser Cut Wooden Desk Name Plate",
    slug: "laser-cut-wooden-desk-name-plate",
    category: "Laser Cutting",
    categorySlug: "laser-cutting",
    price: 549,
    original_price: 799,
    discount: 31,
    rating: 4.8,
    reviews_count: 28,
    stock: 35,
    description: "Angled desktop executive name plaque laser cut from natural maple and dark walnut with personalized laser-engraved typography.",
    image: "/products/v4/laser-cut-wooden-desk-name-plate.jpg",
    image_key: "laser-cut-wooden-desk-name-plate",
    tags: ["laser-cutting", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "lc-008",
    name: "Laser Engraved Wooden Coaster Set",
    title: "Laser Engraved Wooden Coaster Set",
    slug: "laser-engraved-wooden-coaster-set",
    category: "Laser Cutting",
    categorySlug: "laser-cutting",
    price: 449,
    original_price: 649,
    discount: 31,
    rating: 4.9,
    reviews_count: 51,
    stock: 50,
    description: "Set of 6 circular laser-engraved oak drink coasters featuring sacred geometry mandala engravings with matching slotted holder.",
    image: "/products/v4/laser-engraved-wooden-coaster-set.jpg",
    image_key: "laser-engraved-wooden-coaster-set",
    tags: ["laser-cutting", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "lc-009",
    name: "Laser Cut Layered City Skyline",
    title: "Laser Cut Layered City Skyline",
    slug: "laser-cut-layered-city-skyline",
    category: "Laser Cutting",
    categorySlug: "laser-cutting",
    price: 1249,
    original_price: 1749,
    discount: 29,
    rating: 4.9,
    reviews_count: 22,
    stock: 16,
    description: "5-layer architectural 3D cityscape silhouette wall art cut from contrasting tones of stained birch, walnut, and cherry wood.",
    image: "/products/v4/laser-cut-layered-city-skyline.jpg",
    image_key: "laser-cut-layered-city-skyline",
    tags: ["laser-cutting", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "lc-010",
    name: "Laser Cut Wooden Puzzle Box",
    title: "Laser Cut Wooden Puzzle Box",
    slug: "laser-cut-wooden-puzzle-box",
    category: "Laser Cutting",
    categorySlug: "laser-cutting",
    price: 899,
    original_price: 1299,
    discount: 31,
    rating: 5.0,
    reviews_count: 44,
    stock: 20,
    description: "Intricate mechanical secret opening puzzle box with sliding wooden dovetail locks and laser-engraved maze exterior.",
    image: "/products/v4/laser-cut-wooden-puzzle-box.jpg",
    image_key: "laser-cut-wooden-puzzle-box",
    tags: ["laser-cutting", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "lc-011",
    name: "Laser Engraved Bamboo Desk Organizer",
    title: "Laser Engraved Bamboo Desk Organizer",
    slug: "laser-engraved-bamboo-desk-organizer",
    category: "Laser Cutting",
    categorySlug: "laser-cutting",
    price: 699,
    original_price: 999,
    discount: 30,
    rating: 4.8,
    reviews_count: 33,
    stock: 28,
    description: "Eco-friendly solid carbonized bamboo desk organizer tray with laser-engraved topographic elevation contours and phone cradle.",
    image: "/products/v4/laser-engraved-bamboo-desk-organizer.jpg",
    image_key: "laser-engraved-bamboo-desk-organizer",
    tags: ["laser-cutting", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "lc-012",
    name: "Laser Cut Decorative Geometric Lamp",
    title: "Laser Cut Decorative Geometric Lamp",
    slug: "laser-cut-decorative-geometric-lamp",
    category: "Laser Cutting",
    categorySlug: "laser-cutting",
    price: 1399,
    original_price: 1999,
    discount: 30,
    rating: 5.0,
    reviews_count: 39,
    stock: 14,
    description: "Dodecahedron geometric ambient pendant lamp laser cut from 3mm plywood projecting kaleidoscope shadow patterns onto walls.",
    image: "/products/v4/laser-cut-decorative-geometric-lamp.jpg",
    image_key: "laser-cut-decorative-geometric-lamp",
    tags: ["laser-cutting", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "cnc-001",
    name: "CNC V-Carved Solid Walnut Name Plate",
    title: "CNC V-Carved Solid Walnut Name Plate",
    slug: "cnc-v-carved-solid-walnut-name-plate",
    category: "CNC Machining",
    categorySlug: "cnc-machining",
    price: 899,
    original_price: 1299,
    discount: 31,
    rating: 5.0,
    reviews_count: 32,
    stock: 20,
    description: "Solid walnut desktop plaque with deep 90-degree V-bit carved lettering, gold metallic resin inlay, and hand-rubbed oil finish.",
    image: "/products/v4/cnc-v-carved-solid-walnut-name-plate.jpg",
    image_key: "cnc-v-carved-solid-walnut-name-plate",
    tags: ["cnc-machining", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "cnc-002",
    name: "CNC Relief-Carved Wooden Decorative Panel",
    title: "CNC Relief-Carved Wooden Decorative Panel",
    slug: "cnc-relief-carved-wooden-decorative-panel",
    category: "CNC Machining",
    categorySlug: "cnc-machining",
    price: 1699,
    original_price: 2399,
    discount: 29,
    rating: 4.9,
    reviews_count: 21,
    stock: 10,
    description: "Solid teak wood 3D relief wall panel carved with flowing organic parametric waves using CNC ball-nose surface machining.",
    image: "/products/v4/cnc-relief-carved-wooden-decorative-panel.jpg",
    image_key: "cnc-relief-carved-wooden-decorative-panel",
    tags: ["cnc-machining", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "cnc-003",
    name: "CNC Milled Hardwood Keepsake Box",
    title: "CNC Milled Hardwood Keepsake Box",
    slug: "cnc-milled-hardwood-keepsake-box",
    category: "CNC Machining",
    categorySlug: "cnc-machining",
    price: 1149,
    original_price: 1599,
    discount: 28,
    rating: 4.9,
    reviews_count: 27,
    stock: 18,
    description: "Solid white oak jewelry box pocket-milled from a single wood billet with flush neodymium magnetic lid and velvet lining.",
    image: "/products/v4/cnc-milled-hardwood-keepsake-box.jpg",
    image_key: "cnc-milled-hardwood-keepsake-box",
    tags: ["cnc-machining", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "cnc-004",
    name: "CNC Machined 6061 Aluminium L-Bracket",
    title: "CNC Machined 6061 Aluminium L-Bracket",
    slug: "cnc-machined-6061-aluminium-l-bracket",
    category: "CNC Machining",
    categorySlug: "cnc-machining",
    price: 499,
    original_price: 749,
    discount: 33,
    rating: 4.8,
    reviews_count: 48,
    stock: 50,
    description: "Precision milled aerospace 6061-T6 aluminum structural 90-degree corner bracket with fly-cut face finish and chamfered edges.",
    image: "/products/v4/cnc-machined-6061-aluminium-l-bracket.jpg",
    image_key: "cnc-machined-6061-aluminium-l-bracket",
    tags: ["cnc-machining", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "cnc-005",
    name: "CNC Precision Aluminium Fixture Plate",
    title: "CNC Precision Aluminium Fixture Plate",
    slug: "cnc-precision-aluminium-fixture-plate",
    category: "CNC Machining",
    categorySlug: "cnc-machining",
    price: 1499,
    original_price: 2099,
    discount: 29,
    rating: 5.0,
    reviews_count: 16,
    stock: 12,
    description: "Ground flat 6061 tooling plate with precision M6 tapped grid array and locating pin holes for CNC and makerspace workholding.",
    image: "/products/v4/cnc-precision-aluminium-fixture-plate.jpg",
    image_key: "cnc-precision-aluminium-fixture-plate",
    tags: ["cnc-machining", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "cnc-006",
    name: "CNC Machined High-Precision Spur Gear",
    title: "CNC Machined High-Precision Spur Gear",
    slug: "cnc-machined-high-precision-spur-gear",
    category: "CNC Machining",
    categorySlug: "cnc-machining",
    price: 799,
    original_price: 1149,
    discount: 30,
    rating: 4.9,
    reviews_count: 36,
    stock: 25,
    description: "CNC turned and milled 304 stainless steel module-1 spur gear with cut involute teeth, precision center bore, and keyway.",
    image: "/products/v4/cnc-machined-high-precision-spur-gear.jpg",
    image_key: "cnc-machined-high-precision-spur-gear",
    tags: ["cnc-machining", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "cnc-007",
    name: "CNC Machined Aluminium Heat Sink",
    title: "CNC Machined Aluminium Heat Sink",
    slug: "cnc-machined-aluminium-heat-sink",
    category: "CNC Machining",
    categorySlug: "cnc-machining",
    price: 599,
    original_price: 849,
    discount: 29,
    rating: 4.8,
    reviews_count: 40,
    stock: 35,
    description: "Custom milled 6063 aluminum high-density fin thermal heat sink with flat mirror-polished contact plate and black anodized finish.",
    image: "/products/v4/cnc-machined-aluminium-heat-sink.jpg",
    image_key: "cnc-machined-aluminium-heat-sink",
    tags: ["cnc-machining", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "cnc-008",
    name: "CNC Machined Brass Knob Set",
    title: "CNC Machined Brass Knob Set",
    slug: "cnc-machined-brass-knob-set",
    category: "CNC Machining",
    categorySlug: "cnc-machining",
    price: 699,
    original_price: 999,
    discount: 30,
    rating: 5.0,
    reviews_count: 29,
    stock: 24,
    description: "Set of 4 solid brass potentiometer knobs precision CNC lathe-turned with diamond knurled grip pattern and set-screw locking.",
    image: "/products/v4/cnc-machined-brass-knob-set.jpg",
    image_key: "cnc-machined-brass-knob-set",
    tags: ["cnc-machining", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "cnc-009",
    name: "CNC Precision Aluminium Mounting Block",
    title: "CNC Precision Aluminium Mounting Block",
    slug: "cnc-precision-aluminium-mounting-block",
    category: "CNC Machining",
    categorySlug: "cnc-machining",
    price: 549,
    original_price: 799,
    discount: 31,
    rating: 4.8,
    reviews_count: 22,
    stock: 30,
    description: "CNC 4-axis milled aluminum linear rail pillow block mount with precision reamed bearing pockets and counterbored socket holes.",
    image: "/products/v4/cnc-precision-aluminium-mounting-block.jpg",
    image_key: "cnc-precision-aluminium-mounting-block",
    tags: ["cnc-machining", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "cnc-010",
    name: "CNC Machined Stainless Steel Coupling",
    title: "CNC Machined Stainless Steel Coupling",
    slug: "cnc-machined-stainless-steel-coupling",
    category: "CNC Machining",
    categorySlug: "cnc-machining",
    price: 449,
    original_price: 649,
    discount: 31,
    rating: 4.9,
    reviews_count: 38,
    stock: 45,
    description: "Flexible helical beam shaft coupling CNC machined from high-tensile 316 stainless steel for backlash-free stepper motor drive.",
    image: "/products/v4/cnc-machined-stainless-steel-coupling.jpg",
    image_key: "cnc-machined-stainless-steel-coupling",
    tags: ["cnc-machining", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "cnc-011",
    name: "CNC Machined Aluminium Motor Mount",
    title: "CNC Machined Aluminium Motor Mount",
    slug: "cnc-machined-aluminium-motor-mount",
    category: "CNC Machining",
    categorySlug: "cnc-machining",
    price: 649,
    original_price: 899,
    discount: 28,
    rating: 4.8,
    reviews_count: 26,
    stock: 32,
    description: "NEMA 23 stepper motor bracket CNC milled from billet 6061 alloy with cooling airflow vents and red anodized coating.",
    image: "/products/v4/cnc-machined-aluminium-motor-mount.jpg",
    image_key: "cnc-machined-aluminium-motor-mount",
    tags: ["cnc-machining", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "cnc-012",
    name: "CNC Machined Precision Bearing Housing",
    title: "CNC Machined Precision Bearing Housing",
    slug: "cnc-machined-precision-bearing-housing",
    category: "CNC Machining",
    categorySlug: "cnc-machining",
    price: 849,
    original_price: 1199,
    discount: 29,
    rating: 5.0,
    reviews_count: 18,
    stock: 20,
    description: "Double-row ball bearing cartridge housing CNC machined with ±0.005mm bore tolerance and zinc-plated corrosion resistance.",
    image: "/products/v4/cnc-machined-precision-bearing-housing.jpg",
    image_key: "cnc-machined-precision-bearing-housing",
    tags: ["cnc-machining", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "el-001",
    name: "ESP32 Dual-Core IoT Development Board",
    title: "ESP32 Dual-Core IoT Development Board",
    slug: "esp32-dual-core-iot-development-board",
    category: "Electronics",
    categorySlug: "electronics",
    price: 499,
    original_price: 699,
    discount: 29,
    rating: 4.9,
    reviews_count: 112,
    stock: 80,
    description: "ESP-WROOM-32 240MHz dual-core Wi-Fi + Bluetooth IoT micro-controller development board with USB-C and gold header pins.",
    image: "/products/v4/esp32-dual-core-iot-development-board.jpg",
    image_key: "esp32-dual-core-iot-development-board",
    tags: ["electronics", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "el-002",
    name: "37-Piece IoT Sensor Module Starter Kit",
    title: "37-Piece IoT Sensor Module Starter Kit",
    slug: "37-piece-iot-sensor-module-starter-kit",
    category: "Electronics",
    categorySlug: "electronics",
    price: 1499,
    original_price: 2199,
    discount: 32,
    rating: 4.9,
    reviews_count: 83,
    stock: 35,
    description: "Comprehensive assortment of 37 breakout sensors including ultrasonic, temperature/humidity, infrared, relay, and sound modules.",
    image: "/products/v4/37-piece-iot-sensor-module-starter-kit.jpg",
    image_key: "37-piece-iot-sensor-module-starter-kit",
    tags: ["electronics", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "el-003",
    name: "Double-Sided FR4 Prototype PCB Pack",
    title: "Double-Sided FR4 Prototype PCB Pack",
    slug: "double-sided-fr4-prototype-pcb-pack",
    category: "Electronics",
    categorySlug: "electronics",
    price: 299,
    original_price: 449,
    discount: 33,
    rating: 4.8,
    reviews_count: 65,
    stock: 90,
    description: "Set of 10 high-grade green FR4 double-sided plated-through hole prototyping perfboards in assorted project sizes.",
    image: "/products/v4/double-sided-fr4-prototype-pcb-pack.jpg",
    image_key: "double-sided-fr4-prototype-pcb-pack",
    tags: ["electronics", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "el-004",
    name: "Arduino Compatible ATmega328P Microcontroller",
    title: "Arduino Compatible ATmega328P Microcontroller",
    slug: "arduino-compatible-atmega328p-microcontroller",
    category: "Electronics",
    categorySlug: "electronics",
    price: 449,
    original_price: 599,
    discount: 25,
    rating: 4.9,
    reviews_count: 140,
    stock: 70,
    description: "ATmega328P DIP micro-controller board featuring 14 digital I/O pins, 6 PWM channels, and USB interface.",
    image: "/products/v4/arduino-compatible-atmega328p-microcontroller.jpg",
    image_key: "arduino-compatible-atmega328p-microcontroller",
    tags: ["electronics", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "el-005",
    name: "I2C 0.96-Inch OLED Display Module",
    title: "I2C 0.96-Inch OLED Display Module",
    slug: "i2c-096-inch-oled-display-module",
    category: "Electronics",
    categorySlug: "electronics",
    price: 249,
    original_price: 399,
    discount: 38,
    rating: 4.8,
    reviews_count: 88,
    stock: 85,
    description: "Monochrome 128x64 graphic OLED display module with bright cyan pixels and high-speed I2C 4-pin interface.",
    image: "/products/v4/i2c-096-inch-oled-display-module.jpg",
    image_key: "i2c-096-inch-oled-display-module",
    tags: ["electronics", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "el-006",
    name: "ESP32 OLED IoT Display Kit",
    title: "ESP32 OLED IoT Display Kit",
    slug: "esp32-oled-iot-display-kit",
    category: "Electronics",
    categorySlug: "electronics",
    price: 699,
    original_price: 999,
    discount: 30,
    rating: 5.0,
    reviews_count: 49,
    stock: 40,
    description: "All-in-one ESP32 IoT board with integrated 0.96-inch OLED screen, 18650 battery charging circuit, and Wi-Fi antenna.",
    image: "/products/v4/esp32-oled-iot-display-kit.jpg",
    image_key: "esp32-oled-iot-display-kit",
    tags: ["electronics", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "el-007",
    name: "Arduino Sensor Expansion Shield",
    title: "Arduino Sensor Expansion Shield",
    slug: "arduino-sensor-expansion-shield",
    category: "Electronics",
    categorySlug: "electronics",
    price: 349,
    original_price: 499,
    discount: 30,
    rating: 4.7,
    reviews_count: 36,
    stock: 55,
    description: "V5.0 Sensor Shield stacking expansion board breaking out all digital and analog pins to 3-pin G-V-S servo and sensor headers.",
    image: "/products/v4/arduino-sensor-expansion-shield.jpg",
    image_key: "arduino-sensor-expansion-shield",
    tags: ["electronics", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "el-008",
    name: "Raspberry Pi GPIO Prototype Board",
    title: "Raspberry Pi GPIO Prototype Board",
    slug: "raspberry-pi-gpio-prototype-board",
    category: "Electronics",
    categorySlug: "electronics",
    price: 399,
    original_price: 599,
    discount: 33,
    rating: 4.8,
    reviews_count: 31,
    stock: 45,
    description: "40-pin GPIO breakout prototyping HAT with labeled power rails, terminal screw blocks, and solder pad breadboard matrix.",
    image: "/products/v4/raspberry-pi-gpio-prototype-board.jpg",
    image_key: "raspberry-pi-gpio-prototype-board",
    tags: ["electronics", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "el-009",
    name: "8-Channel Relay Module",
    title: "8-Channel Relay Module",
    slug: "8-channel-relay-module",
    category: "Electronics",
    categorySlug: "electronics",
    price: 549,
    original_price: 799,
    discount: 31,
    rating: 4.9,
    reviews_count: 57,
    stock: 38,
    description: "5V 10A 8-channel relay board with optical isolation, status indicator LEDs, and screw terminals for home automation switching.",
    image: "/products/v4/8-channel-relay-module.jpg",
    image_key: "8-channel-relay-module",
    tags: ["electronics", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "el-010",
    name: "LoRa Wireless Communication Module",
    title: "LoRa Wireless Communication Module",
    slug: "lora-wireless-communication-module",
    category: "Electronics",
    categorySlug: "electronics",
    price: 799,
    original_price: 1149,
    discount: 30,
    rating: 5.0,
    reviews_count: 27,
    stock: 25,
    description: "SX1276 868/915MHz long-range SPI LoRa transceiver module with IPEX antenna connector for IoT telemetry networks.",
    image: "/products/v4/lora-wireless-communication-module.jpg",
    image_key: "lora-wireless-communication-module",
    tags: ["electronics", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "el-011",
    name: "USB-C Power Delivery Development Board",
    title: "USB-C Power Delivery Development Board",
    slug: "usb-c-power-delivery-development-board",
    category: "Electronics",
    categorySlug: "electronics",
    price: 449,
    original_price: 649,
    discount: 31,
    rating: 4.8,
    reviews_count: 43,
    stock: 42,
    description: "Programmable USB-PD 3.0 trigger module with rotary dial to negotiate 5V, 9V, 12V, 15V, and 20V DC output up to 100W.",
    image: "/products/v4/usb-c-power-delivery-development-board.jpg",
    image_key: "usb-c-power-delivery-development-board",
    tags: ["electronics", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "el-012",
    name: "4-Channel Motor Driver Module",
    title: "4-Channel Motor Driver Module",
    slug: "4-channel-motor-driver-module",
    category: "Electronics",
    categorySlug: "electronics",
    price: 499,
    original_price: 749,
    discount: 33,
    rating: 4.9,
    reviews_count: 50,
    stock: 35,
    description: "L298N dual H-bridge motor driver board capable of driving 4 DC gear motors or 2 stepper motors with onboard 5V regulator.",
    image: "/products/v4/4-channel-motor-driver-module.jpg",
    image_key: "4-channel-motor-driver-module",
    tags: ["electronics", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "dr-001",
    name: "5-Inch FPV Racing 3K Carbon Fiber Drone Frame",
    title: "5-Inch FPV Racing 3K Carbon Fiber Drone Frame",
    slug: "5-inch-fpv-racing-3k-carbon-fiber-drone-frame",
    category: "Drones & Parts",
    categorySlug: "drones-parts",
    price: 1899,
    original_price: 2599,
    discount: 27,
    rating: 5.0,
    reviews_count: 64,
    stock: 20,
    description: "True-X 225mm freestyle FPV frame cut from 5mm 3K matte twill carbon fiber with purple CNC anodized aluminum standoffs.",
    image: "/products/v4/5-inch-fpv-racing-3k-carbon-fiber-drone-frame.jpg",
    image_key: "5-inch-fpv-racing-3k-carbon-fiber-drone-frame",
    tags: ["drones-parts", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "dr-002",
    name: "2207 2450KV High-Power Brushless Drone Motor",
    title: "2207 2450KV High-Power Brushless Drone Motor",
    slug: "2207-2450kv-high-power-brushless-drone-motor",
    category: "Drones & Parts",
    categorySlug: "drones-parts",
    price: 899,
    original_price: 1299,
    discount: 31,
    rating: 4.9,
    reviews_count: 75,
    stock: 48,
    description: "High-thrust 2207 2450KV racing brushless motor featuring curved N52SH arc magnets, single-strand copper coils, and titanium shaft.",
    image: "/products/v4/2207-2450kv-high-power-brushless-drone-motor.jpg",
    image_key: "2207-2450kv-high-power-brushless-drone-motor",
    tags: ["drones-parts", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "dr-003",
    name: "5-Inch Tri-Blade FPV Drone Propellers Pack",
    title: "5-Inch Tri-Blade FPV Drone Propellers Pack",
    slug: "5-inch-tri-blade-fpv-drone-propellers-pack",
    category: "Drones & Parts",
    categorySlug: "drones-parts",
    price: 349,
    original_price: 499,
    discount: 30,
    rating: 4.8,
    reviews_count: 92,
    stock: 100,
    description: "Set of 4 pairs of 51466 polycarbonate tri-blade aerodynamic racing propellers in neon cyan and orange.",
    image: "/products/v4/5-inch-tri-blade-fpv-drone-propellers-pack.jpg",
    image_key: "5-inch-tri-blade-fpv-drone-propellers-pack",
    tags: ["drones-parts", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "dr-004",
    name: "30A 4-in-1 BLHeli_S Electronic Speed Controller",
    title: "30A 4-in-1 BLHeli_S Electronic Speed Controller",
    slug: "30a-4-in-1-blheli-s-electronic-speed-controller",
    category: "Drones & Parts",
    categorySlug: "drones-parts",
    price: 1599,
    original_price: 2299,
    discount: 30,
    rating: 4.9,
    reviews_count: 41,
    stock: 25,
    description: "30.5x30.5mm 4-in-1 30A brushless ESC with DShot600 support, high-power MOSFET transistors, and gold solder pads.",
    image: "/products/v4/30a-4-in-1-blheli-s-electronic-speed-controller.jpg",
    image_key: "30a-4-in-1-blheli-s-electronic-speed-controller",
    tags: ["drones-parts", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "dr-005",
    name: "Omnidirectional 5.8GHz FPV Cloverleaf Antenna",
    title: "Omnidirectional 5.8GHz FPV Cloverleaf Antenna",
    slug: "omnidirectional-58ghz-fpv-cloverleaf-antenna",
    category: "Drones & Parts",
    categorySlug: "drones-parts",
    price: 499,
    original_price: 749,
    discount: 33,
    rating: 4.8,
    reviews_count: 53,
    stock: 45,
    description: "Right-hand circular polarized (RHCP) 5.8GHz video transmitter antenna with gold SMA connector and flexible red stem.",
    image: "/products/v4/omnidirectional-58ghz-fpv-cloverleaf-antenna.jpg",
    image_key: "omnidirectional-58ghz-fpv-cloverleaf-antenna",
    tags: ["drones-parts", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "dr-006",
    name: "FPV Drone Motor Mount Set",
    title: "FPV Drone Motor Mount Set",
    slug: "fpv-drone-motor-mount-set",
    category: "Drones & Parts",
    categorySlug: "drones-parts",
    price: 399,
    original_price: 599,
    discount: 33,
    rating: 4.7,
    reviews_count: 29,
    stock: 40,
    description: "Set of 4 vibration-dampening TPU motor base guards and 16x16mm / 19x19mm aluminium adapter plates in electric blue.",
    image: "/products/v4/fpv-drone-motor-mount-set.jpg",
    image_key: "fpv-drone-motor-mount-set",
    tags: ["drones-parts", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "dr-007",
    name: "5-Inch FPV Drone Propeller Guard",
    title: "5-Inch FPV Drone Propeller Guard",
    slug: "5-inch-fpv-drone-propeller-guard",
    category: "Drones & Parts",
    categorySlug: "drones-parts",
    price: 549,
    original_price: 799,
    discount: 31,
    rating: 4.8,
    reviews_count: 34,
    stock: 30,
    description: "Full-duct 360-degree injection molded composite propeller bumpers for indoor cinewhoop flying and impact protection.",
    image: "/products/v4/5-inch-fpv-drone-propeller-guard.jpg",
    image_key: "5-inch-fpv-drone-propeller-guard",
    tags: ["drones-parts", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "dr-008",
    name: "Carbon Fiber Drone Arm Set",
    title: "Carbon Fiber Drone Arm Set",
    slug: "carbon-fiber-drone-arm-set",
    category: "Drones & Parts",
    categorySlug: "drones-parts",
    price: 699,
    original_price: 999,
    discount: 30,
    rating: 4.9,
    reviews_count: 46,
    stock: 35,
    description: "Pack of 4 replacement 6mm heavy-duty 3K carbon fiber quadcopter arms with chamfered edges and pre-drilled motor slots.",
    image: "/products/v4/carbon-fiber-drone-arm-set.jpg",
    image_key: "carbon-fiber-drone-arm-set",
    tags: ["drones-parts", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "dr-009",
    name: "FPV Drone Battery Strap Kit",
    title: "FPV Drone Battery Strap Kit",
    slug: "fpv-drone-battery-strap-kit",
    category: "Drones & Parts",
    categorySlug: "drones-parts",
    price: 249,
    original_price: 399,
    discount: 38,
    rating: 4.9,
    reviews_count: 70,
    stock: 80,
    description: "Set of 4 Kevlar-reinforced anti-slip rubberized LiPo battery straps with steel metal buckle and silicone grip pad.",
    image: "/products/v4/fpv-drone-battery-strap-kit.jpg",
    image_key: "fpv-drone-battery-strap-kit",
    tags: ["drones-parts", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "dr-010",
    name: "Drone GPS Module",
    title: "Drone GPS Module",
    slug: "drone-gps-module",
    category: "Drones & Parts",
    categorySlug: "drones-parts",
    price: 899,
    original_price: 1299,
    discount: 31,
    rating: 4.9,
    reviews_count: 38,
    stock: 28,
    description: "M8N micro GPS compass module with ceramic patch antenna and onboard flash memory for autonomous drone rescue return.",
    image: "/products/v4/drone-gps-module.jpg",
    image_key: "drone-gps-module",
    tags: ["drones-parts", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "dr-011",
    name: "FPV Camera Mount",
    title: "FPV Camera Mount",
    slug: "fpv-camera-mount",
    category: "Drones & Parts",
    categorySlug: "drones-parts",
    price: 349,
    original_price: 499,
    discount: 30,
    rating: 4.8,
    reviews_count: 30,
    stock: 50,
    description: "Adjustable 25 to 60-degree angle micro FPV camera bracket 3D printed in flexible durable neon green TPU.",
    image: "/products/v4/fpv-camera-mount.jpg",
    image_key: "fpv-camera-mount",
    tags: ["drones-parts", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "dr-012",
    name: "Brushless Motor Propeller Adapter",
    title: "Brushless Motor Propeller Adapter",
    slug: "brushless-motor-propeller-adapter",
    category: "Drones & Parts",
    categorySlug: "drones-parts",
    price: 299,
    original_price: 449,
    discount: 33,
    rating: 4.7,
    reviews_count: 45,
    stock: 60,
    description: "Set of 4 CNC machined M5 low-profile anodized aluminium propeller lock nuts with flanged nylon self-locking insert.",
    image: "/products/v4/brushless-motor-propeller-adapter.jpg",
    image_key: "brushless-motor-propeller-adapter",
    tags: ["drones-parts", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "ac-001",
    name: "Crystal Clear Cast Acrylic Showcase Cube Box",
    title: "Crystal Clear Cast Acrylic Showcase Cube Box",
    slug: "crystal-clear-cast-acrylic-showcase-cube-box",
    category: "Acrylic Products",
    categorySlug: "acrylic-products",
    price: 899,
    original_price: 1299,
    discount: 31,
    rating: 4.9,
    reviews_count: 38,
    stock: 25,
    description: "Museum-grade 5-sided optical cast clear acrylic display cube with diamond polished edges and glossy black acrylic pedestal base.",
    image: "/products/v4/crystal-clear-cast-acrylic-showcase-cube-box.jpg",
    image_key: "crystal-clear-cast-acrylic-showcase-cube-box",
    tags: ["acrylic-products", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "ac-002",
    name: "Laser Engraved Beveled Acrylic Award Trophy",
    title: "Laser Engraved Beveled Acrylic Award Trophy",
    slug: "laser-engraved-beveled-acrylic-award-trophy",
    category: "Acrylic Products",
    categorySlug: "acrylic-products",
    price: 999,
    original_price: 1499,
    discount: 33,
    rating: 5.0,
    reviews_count: 47,
    stock: 30,
    description: "20mm thick crystal-faceted octagonal acrylic recognition trophy with frosted laser-engraved laurel crest and weighted base.",
    image: "/products/v4/laser-engraved-beveled-acrylic-award-trophy.jpg",
    image_key: "laser-engraved-beveled-acrylic-award-trophy",
    tags: ["acrylic-products", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "ac-003",
    name: "High-Clarity Heavy Duty Acrylic Sneeze Shield",
    title: "High-Clarity Heavy Duty Acrylic Sneeze Shield",
    slug: "high-clarity-heavy-duty-acrylic-sneeze-shield",
    category: "Acrylic Products",
    categorySlug: "acrylic-products",
    price: 1299,
    original_price: 1899,
    discount: 32,
    rating: 4.8,
    reviews_count: 26,
    stock: 20,
    description: "Freestanding 5mm shatter-resistant acrylic counter protective barrier shield with document pass-through slot and interlocking feet.",
    image: "/products/v4/high-clarity-heavy-duty-acrylic-sneeze-shield.jpg",
    image_key: "high-clarity-heavy-duty-acrylic-sneeze-shield",
    tags: ["acrylic-products", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "ac-004",
    name: "Desktop Acrylic Slanted Brochure & Menu Holder",
    title: "Desktop Acrylic Slanted Brochure & Menu Holder",
    slug: "desktop-acrylic-slanted-brochure-menu-holder",
    category: "Acrylic Products",
    categorySlug: "acrylic-products",
    price: 349,
    original_price: 499,
    discount: 30,
    rating: 4.8,
    reviews_count: 55,
    stock: 60,
    description: "L-shaped slanted freestanding clear acrylic flyer and menu display stand for A4 and letter size documents.",
    image: "/products/v4/desktop-acrylic-slanted-brochure-menu-holder.jpg",
    image_key: "desktop-acrylic-slanted-brochure-menu-holder",
    tags: ["acrylic-products", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "ac-005",
    name: "Multi-Tiered Clear Acrylic Cosmetic Display Riser",
    title: "Multi-Tiered Clear Acrylic Cosmetic Display Riser",
    slug: "multi-tiered-clear-acrylic-cosmetic-display-riser",
    category: "Acrylic Products",
    categorySlug: "acrylic-products",
    price: 749,
    original_price: 1049,
    discount: 29,
    rating: 4.9,
    reviews_count: 36,
    stock: 35,
    description: "3-tier stepped transparent acrylic display shelf riser stand for perfumes, collectibles, miniatures, and retail showcases.",
    image: "/products/v4/multi-tiered-clear-acrylic-cosmetic-display-riser.jpg",
    image_key: "multi-tiered-clear-acrylic-cosmetic-display-riser",
    tags: ["acrylic-products", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "ac-006",
    name: "Clear Acrylic Business Card Holder",
    title: "Clear Acrylic Business Card Holder",
    slug: "clear-acrylic-business-card-holder",
    category: "Acrylic Products",
    categorySlug: "acrylic-products",
    price: 249,
    original_price: 399,
    discount: 38,
    rating: 4.8,
    reviews_count: 62,
    stock: 75,
    description: "Minimalist angled desktop business card holder with flame-polished edges and high capacity 60-card compartment.",
    image: "/products/v4/clear-acrylic-business-card-holder.jpg",
    image_key: "clear-acrylic-business-card-holder",
    tags: ["acrylic-products", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "ac-007",
    name: "Acrylic QR Code Display Stand",
    title: "Acrylic QR Code Display Stand",
    slug: "acrylic-qr-code-display-stand",
    category: "Acrylic Products",
    categorySlug: "acrylic-products",
    price: 449,
    original_price: 649,
    discount: 31,
    rating: 4.9,
    reviews_count: 44,
    stock: 50,
    description: "Dual-layer modern QR payment stand with mirror gold acrylic backer and laser-etched clear acrylic top plate on wooden base.",
    image: "/products/v4/acrylic-qr-code-display-stand.jpg",
    image_key: "acrylic-qr-code-display-stand",
    tags: ["acrylic-products", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "ac-008",
    name: "Acrylic Product Display Box",
    title: "Acrylic Product Display Box",
    slug: "acrylic-product-display-box",
    category: "Acrylic Products",
    categorySlug: "acrylic-products",
    price: 799,
    original_price: 1149,
    discount: 30,
    rating: 4.9,
    reviews_count: 30,
    stock: 28,
    description: "Dustproof transparent acrylic showcase box with sliding front access door and LED top lighting strip.",
    image: "/products/v4/acrylic-product-display-box.jpg",
    image_key: "acrylic-product-display-box",
    tags: ["acrylic-products", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "ac-009",
    name: "Acrylic Jewelry Display Stand",
    title: "Acrylic Jewelry Display Stand",
    slug: "acrylic-jewelry-display-stand",
    category: "Acrylic Products",
    categorySlug: "acrylic-products",
    price: 599,
    original_price: 849,
    discount: 29,
    rating: 5.0,
    reviews_count: 29,
    stock: 32,
    description: "T-bar clear and frosted acrylic necklace and bracelet jewelry organizer stand with stable round base.",
    image: "/products/v4/acrylic-jewelry-display-stand.jpg",
    image_key: "acrylic-jewelry-display-stand",
    tags: ["acrylic-products", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "ac-010",
    name: "Acrylic Menu Stand",
    title: "Acrylic Menu Stand",
    slug: "acrylic-menu-stand",
    category: "Acrylic Products",
    categorySlug: "acrylic-products",
    price: 399,
    original_price: 599,
    discount: 33,
    rating: 4.7,
    reviews_count: 41,
    stock: 60,
    description: "Double-sided vertical T-shape clear acrylic tabletop sign holder with magnetic top closure.",
    image: "/products/v4/acrylic-menu-stand.jpg",
    image_key: "acrylic-menu-stand",
    tags: ["acrylic-products", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "ac-011",
    name: "Acrylic Desktop Sign Holder",
    title: "Acrylic Desktop Sign Holder",
    slug: "acrylic-desktop-sign-holder",
    category: "Acrylic Products",
    categorySlug: "acrylic-products",
    price: 299,
    original_price: 449,
    discount: 33,
    rating: 4.8,
    reviews_count: 50,
    stock: 65,
    description: "V-shaped slanted clear acrylic name card and table number holder with polished beveled corners.",
    image: "/products/v4/acrylic-desktop-sign-holder.jpg",
    image_key: "acrylic-desktop-sign-holder",
    tags: ["acrylic-products", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "ac-012",
    name: "Multi-Level Acrylic Display Shelf",
    title: "Multi-Level Acrylic Display Shelf",
    slug: "multi-level-acrylic-display-shelf",
    category: "Acrylic Products",
    categorySlug: "acrylic-products",
    price: 1099,
    original_price: 1599,
    discount: 31,
    rating: 4.9,
    reviews_count: 24,
    stock: 18,
    description: "4-tier semi-circular transparent acrylic retail product display stand with stainless steel standoff pillars.",
    image: "/products/v4/multi-level-acrylic-display-shelf.jpg",
    image_key: "multi-level-acrylic-display-shelf",
    tags: ["acrylic-products", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "kit-001",
    name: "Autonomous 4WD Smart Robotic STEM Starter Kit",
    title: "Autonomous 4WD Smart Robotic STEM Starter Kit",
    slug: "autonomous-4wd-smart-robotic-stem-starter-kit",
    category: "DIY Kits",
    categorySlug: "diy-kits",
    price: 1999,
    original_price: 2899,
    discount: 31,
    rating: 5.0,
    reviews_count: 84,
    stock: 25,
    description: "Complete robotic vehicle kit with dual acrylic chassis, 4 TT gearmotors, L298N driver, ultrasonic obstacle sensor, and Arduino.",
    image: "/products/v4/autonomous-4wd-smart-robotic-stem-starter-kit.jpg",
    image_key: "autonomous-4wd-smart-robotic-stem-starter-kit",
    tags: ["diy-kits", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "kit-002",
    name: "Educational Electronics Soldering Practice Kit",
    title: "Educational Electronics Soldering Practice Kit",
    slug: "educational-electronics-soldering-practice-kit",
    category: "DIY Kits",
    categorySlug: "diy-kits",
    price: 499,
    original_price: 749,
    discount: 33,
    rating: 4.9,
    reviews_count: 92,
    stock: 60,
    description: "Hands-on soldering trainer board with flashing RGB LEDs, 555 timer IC, resistors, capacitors, buzzer, and instructional manual.",
    image: "/products/v4/educational-electronics-soldering-practice-kit.jpg",
    image_key: "educational-electronics-soldering-practice-kit",
    tags: ["diy-kits", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "kit-003",
    name: "DIY Portable Bluetooth Stereo Speaker Maker Kit",
    title: "DIY Portable Bluetooth Stereo Speaker Maker Kit",
    slug: "diy-portable-bluetooth-stereo-speaker-maker-kit",
    category: "DIY Kits",
    categorySlug: "diy-kits",
    price: 1399,
    original_price: 1999,
    discount: 30,
    rating: 4.9,
    reviews_count: 46,
    stock: 30,
    description: "Build-your-own wooden Bluetooth 5.0 speaker box kit with twin 2-inch 5W full-range audio drivers, rechargeable battery, and volume knob.",
    image: "/products/v4/diy-portable-bluetooth-stereo-speaker-maker-kit.jpg",
    image_key: "diy-portable-bluetooth-stereo-speaker-maker-kit",
    tags: ["diy-kits", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "kit-004",
    name: "Miniature Solar Powered STEM Rover Buggy Kit",
    title: "Miniature Solar Powered STEM Rover Buggy Kit",
    slug: "miniature-solar-powered-stem-rover-buggy-kit",
    category: "DIY Kits",
    categorySlug: "diy-kits",
    price: 599,
    original_price: 849,
    discount: 29,
    rating: 4.8,
    reviews_count: 57,
    stock: 45,
    description: "Solar energy science education rover buggy kit with monocrystalline solar panel, DC mini motor, nylon reduction gears, and wheels.",
    image: "/products/v4/miniature-solar-powered-stem-rover-buggy-kit.jpg",
    image_key: "miniature-solar-powered-stem-rover-buggy-kit",
    tags: ["diy-kits", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "kit-005",
    name: "Smart Weather Station IoT ESP8266 Maker Kit",
    title: "Smart Weather Station IoT ESP8266 Maker Kit",
    slug: "smart-weather-station-iot-esp8266-maker-kit",
    category: "DIY Kits",
    categorySlug: "diy-kits",
    price: 1249,
    original_price: 1799,
    discount: 31,
    rating: 5.0,
    reviews_count: 39,
    stock: 28,
    description: "Wi-Fi weather station kit with ESP8266 NodeMCU, DHT11 temp/humidity sensor, BMP280 barometer, 0.96 OLED display, and jumper wires.",
    image: "/products/v4/smart-weather-station-iot-esp8266-maker-kit.jpg",
    image_key: "smart-weather-station-iot-esp8266-maker-kit",
    tags: ["diy-kits", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "kit-006",
    name: "DIY Arduino Robot Car Kit",
    title: "DIY Arduino Robot Car Kit",
    slug: "diy-arduino-robot-car-kit",
    category: "DIY Kits",
    categorySlug: "diy-kits",
    price: 1799,
    original_price: 2499,
    discount: 28,
    rating: 4.9,
    reviews_count: 66,
    stock: 22,
    description: "Smart 2WD programmable balance and obstacle avoiding robotic car with line tracker module, IR remote, and servo pan-tilt sensor mount.",
    image: "/products/v4/diy-arduino-robot-car-kit.jpg",
    image_key: "diy-arduino-robot-car-kit",
    tags: ["diy-kits", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "kit-007",
    name: "DIY Mini Weather Station Kit",
    title: "DIY Mini Weather Station Kit",
    slug: "diy-mini-weather-station-kit",
    category: "DIY Kits",
    categorySlug: "diy-kits",
    price: 999,
    original_price: 1449,
    discount: 31,
    rating: 4.8,
    reviews_count: 33,
    stock: 35,
    description: "Compact desktop indoor climate monitor kit featuring LCD1602 screen, digital humidity sensor, real-time clock module, and acrylic case.",
    image: "/products/v4/diy-mini-weather-station-kit.jpg",
    image_key: "diy-mini-weather-station-kit",
    tags: ["diy-kits", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "kit-008",
    name: "DIY LED Matrix Display Kit",
    title: "DIY LED Matrix Display Kit",
    slug: "diy-led-matrix-display-kit",
    category: "DIY Kits",
    categorySlug: "diy-kits",
    price: 799,
    original_price: 1149,
    discount: 30,
    rating: 4.9,
    reviews_count: 48,
    stock: 40,
    description: "MAX7219 8x32 cascading red LED matrix scrolling message ticker kit with microcontroller controller and solderable ribbon cables.",
    image: "/products/v4/diy-led-matrix-display-kit.jpg",
    image_key: "diy-led-matrix-display-kit",
    tags: ["diy-kits", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "kit-009",
    name: "DIY Smart Plant Monitoring Kit",
    title: "DIY Smart Plant Monitoring Kit",
    slug: "diy-smart-plant-monitoring-kit",
    category: "DIY Kits",
    categorySlug: "diy-kits",
    price: 899,
    original_price: 1299,
    discount: 31,
    rating: 5.0,
    reviews_count: 29,
    stock: 30,
    description: "Automated plant watering kit with capacitive soil moisture probe, 5V mini submersible water pump, relay, and OLED status screen.",
    image: "/products/v4/diy-smart-plant-monitoring-kit.jpg",
    image_key: "diy-smart-plant-monitoring-kit",
    tags: ["diy-kits", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "kit-010",
    name: "DIY Line Following Robot Kit",
    title: "DIY Line Following Robot Kit",
    slug: "diy-line-following-robot-kit",
    category: "DIY Kits",
    categorySlug: "diy-kits",
    price: 649,
    original_price: 899,
    discount: 28,
    rating: 4.8,
    reviews_count: 53,
    stock: 45,
    description: "Analog sensor-based optical line following car kit with dual photoresistors, LM393 comparator circuit, motors, and battery holder.",
    image: "/products/v4/diy-line-following-robot-kit.jpg",
    image_key: "diy-line-following-robot-kit",
    tags: ["diy-kits", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "kit-011",
    name: "DIY Solar Tracking Kit",
    title: "DIY Solar Tracking Kit",
    slug: "diy-solar-tracking-kit",
    category: "DIY Kits",
    categorySlug: "diy-kits",
    price: 1499,
    original_price: 2199,
    discount: 32,
    rating: 4.9,
    reviews_count: 25,
    stock: 18,
    description: "Dual-axis automatic solar tracker kit with 4 LDR light sensors, twin micro servo motors, solar panel, and Arduino controller.",
    image: "/products/v4/diy-solar-tracking-kit.jpg",
    image_key: "diy-solar-tracking-kit",
    tags: ["diy-kits", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
  {
    id: "kit-012",
    name: "DIY Bluetooth Home Automation Kit",
    title: "DIY Bluetooth Home Automation Kit",
    slug: "diy-bluetooth-home-automation-kit",
    category: "DIY Kits",
    categorySlug: "diy-kits",
    price: 1199,
    original_price: 1699,
    discount: 29,
    rating: 5.0,
    reviews_count: 37,
    stock: 25,
    description: "4-channel smartphone Bluetooth wireless appliance control kit with HC-05 module, relay board, 12V power supply, and smartphone app.",
    image: "/products/v4/diy-bluetooth-home-automation-kit.jpg",
    image_key: "diy-bluetooth-home-automation-kit",
    tags: ["diy-kits", "makerspace", "idea-lab"],
    features: ["Precision Manufactured", "AICTE IDEA Lab Certified", "Ready for Deployment"],
    specs: { "Material": "Industrial Grade", "Origin": "AICTE IDEA Lab", "Quality": "100% Tested" }
  },
];

export const CATEGORY_META = {
  "3d-printing": {
    name: "3D Printing",
    description: "FDM & SLA high-precision 3D printed components, prototypes, and fixtures.",
    heroImage: "/products/v4/3d-printed-geometric-spiral-vase.jpg"
  },
  "laser-cutting": {
    name: "Laser Cutting",
    description: "Laser cut wood, acrylic, layered art, and bespoke flat-pack enclosures.",
    heroImage: "/products/v4/laser-cut-tree-of-life-wooden-led-lamp.jpg"
  },
  "cnc-machining": {
    name: "CNC Machining",
    description: "Subtractive milled metals, fixtures, gears, and relief hardwood panels.",
    heroImage: "/products/v4/cnc-v-carved-solid-walnut-name-plate.jpg"
  },
  "electronics": {
    name: "Electronics",
    description: "Microcontroller boards, sensor breakout kits, and prototype PCBs.",
    heroImage: "/products/v4/esp32-dual-core-iot-development-board.jpg"
  },
  "drones-parts": {
    name: "Drones & Parts",
    description: "FPV racing frames, brushless motors, propellers, and flight accessories.",
    heroImage: "/products/v4/5-inch-fpv-racing-3k-carbon-fiber-drone-frame.jpg"
  },
  "acrylic-products": {
    name: "Acrylic Products",
    description: "Optical clear display cubes, faceted trophies, and desktop organizers.",
    heroImage: "/products/v4/crystal-clear-cast-acrylic-showcase-cube-box.jpg"
  },
  "diy-kits": {
    name: "DIY Kits",
    description: "Complete hands-on STEM robotics, solar rovers, and IoT project kits.",
    heroImage: "/products/v4/autonomous-4wd-smart-robotic-stem-starter-kit.jpg"
  }
};

export function formatProductSlug(product: { slug?: string; name?: string; title?: string }): string {
  if (product.slug) return product.slug;
  const raw = product.title || product.name || "product";
  return raw.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

export function sanitizeProduct(p: any): Product {
  return {
    ...p,
    title: p.title || p.name,
    name: p.name || p.title,
    categorySlug: p.categorySlug || p.category_slug,
    image: p.image || `/products/v4/${p.slug}.jpg`
  };
}

export async function getProducts(): Promise<Product[]> {
  return DEFAULT_CATALOG_PRODUCTS.map(sanitizeProduct);
}

export async function getProductBySlug(slug: string): Promise<Product | null> {
  const p = DEFAULT_CATALOG_PRODUCTS.find(x => x.slug === slug);
  return p ? sanitizeProduct(p) : null;
}

export const productsQuery = {
  queryKey: ["products"],
  queryFn: getProducts,
  initialData: DEFAULT_CATALOG_PRODUCTS.map(sanitizeProduct),
  staleTime: Infinity
};
