// Clean 1-to-1 Product Image Resolution
export const EXACT_SLUG_IMAGE_MAP: Record<string, string> = {
  "3d-printed-winged-mythical-dragon-sculpture": "/products/v5/3d-printed-winged-mythical-dragon-sculpture.jpg",
  "3d-printed-cute-animal-cable-organizer-clips": "/products/v5/3d-printed-cute-animal-cable-organizer-clips.jpg",
  "3d-printed-institutional-desktop-nameplate": "/products/v5/3d-printed-institutional-desktop-nameplate.jpg",
  "3d-printed-ergonomic-bed-scraper-tool": "/products/v5/3d-printed-ergonomic-bed-scraper-tool.jpg",
  "3d-printed-dual-tone-emblem-coaster-token": "/products/v5/3d-printed-dual-tone-emblem-coaster-token.jpg",
  "3d-printed-personalized-vertical-name-keychain": "/products/v5/3d-printed-personalized-vertical-name-keychain.jpg",
  "3d-printed-custom-oval-name-badge": "/products/v5/3d-printed-custom-oval-name-badge.jpg",
  "3d-printed-custom-executive-name-tag": "/products/v5/3d-printed-custom-executive-name-tag.jpg",
  "3d-printed-articulated-folding-name-banner": "/products/v5/3d-printed-articulated-folding-name-banner.jpg",
  "3d-printed-custom-cable-label-clip-set": "/products/v5/3d-printed-custom-cable-label-clip-set.jpg",
  "3d-printed-humanoid-seated-succulent-planter-set": "/products/v5/3d-printed-humanoid-seated-succulent-planter-set.jpg",
  "3d-printed-modular-outdoor-geometric-wall-planter": "/products/v5/3d-printed-modular-outdoor-geometric-wall-planter.jpg",
  "3d-printed-faceted-wall-planter-ambient-sconce": "/products/v5/3d-printed-faceted-wall-planter-ambient-sconce.jpg",
  "3d-printed-foldable-pocket-phone-stand-keychain": "/products/v5/3d-printed-foldable-pocket-phone-stand-keychain.jpg",
  "3d-printed-sculptural-ribbon-phone-stand": "/products/v5/3d-printed-sculptural-ribbon-phone-stand.jpg",
  "3d-printed-low-poly-faceted-succulent-planter": "/products/v5/3d-printed-low-poly-faceted-succulent-planter.jpg",
  "3d-printed-batwing-desktop-headphone-stand": "/products/v5/3d-printed-batwing-desktop-headphone-stand.jpg",
  "3d-printed-profile-face-eyeglass-stand": "/products/v5/3d-printed-profile-face-eyeglass-stand.jpg",
  "3d-printed-dancing-cat-earbud-pen-holder": "/products/v5/3d-printed-dancing-cat-earbud-pen-holder.jpg",
  "3d-printed-mini-octopus-toothpick-holder-pair": "/products/v5/3d-printed-mini-octopus-toothpick-holder-pair.jpg",
  "3d-printed-hedgehog-pencil-caddy-desk-organizer": "/products/v5/3d-printed-hedgehog-pencil-caddy-desk-organizer.jpg",
  "3d-printed-cute-animal-miniature-phone-stand-pair": "/products/v5/3d-printed-cute-animal-miniature-phone-stand-pair.jpg",
  "3d-printed-cartoon-eyeglass-rest-desk-tray": "/products/v5/3d-printed-cartoon-eyeglass-rest-desk-tray.jpg",
  "3d-printed-climbing-figure-smartphone-stand-trio": "/products/v5/3d-printed-climbing-figure-smartphone-stand-trio.jpg",
  "3d-printed-ghost-desktop-pen-rest": "/products/v5/3d-printed-ghost-desktop-pen-rest.jpg",
  "3d-printed-infinity-loop-stationery-organizer": "/products/v5/3d-printed-infinity-loop-stationery-organizer.jpg",
  "3d-printed-avengers-emblem-desk-pen-caddy": "/products/v5/3d-printed-avengers-emblem-desk-pen-caddy.jpg",
  "3d-printed-rounded-modular-wall-terrarium-planters": "/products/v5/3d-printed-rounded-modular-wall-terrarium-planters.jpg",
  "3d-printed-fluted-spiral-flower-vase-pair": "/products/v5/3d-printed-fluted-spiral-flower-vase-pair.jpg",
  "3d-printed-sci-fi-reactor-core-art-model": "/products/v5/3d-printed-sci-fi-reactor-core-art-model.jpg",
  "3d-printed-bold-custom-name-keychain": "/products/v5/3d-printed-bold-custom-name-keychain.jpg",
  "laser-cut-plywood-qr-code-feedback-stand": "/products/v5/laser-cut-plywood-qr-code-feedback-stand.jpg",
  "laser-cut-geometric-wooden-desk-pen-organizer-trio": "/products/v5/laser-cut-geometric-wooden-desk-pen-organizer-trio.jpg",
  "laser-engraved-acrylic-aicte-idea-lab-emblem-plaque": "/products/v5/laser-engraved-acrylic-aicte-idea-lab-emblem-plaque.jpg",
  "laser-engraved-acrylic-institutional-desk-nameplate": "/products/v5/laser-engraved-acrylic-institutional-desk-nameplate.jpg",
  "laser-engraved-hardwood-desk-block-plaque": "/products/v5/laser-engraved-hardwood-desk-block-plaque.jpg",
  "laser-engraved-oval-hardwood-name-keychain": "/products/v5/laser-engraved-oval-hardwood-name-keychain.jpg",
  "laser-cut-supercar-silhouette-wooden-wall-art": "/products/v5/laser-cut-supercar-silhouette-wooden-wall-art.jpg",
  "laser-cut-layered-wooden-llama-desk-companion": "/products/v5/laser-cut-layered-wooden-llama-desk-companion.jpg",
  "laser-cut-wooden-wildflower-desk-centerpiece": "/products/v5/laser-cut-wooden-wildflower-desk-centerpiece.jpg",
  "laser-cut-wooden-bookmark-paperclip-set": "/products/v5/laser-cut-wooden-bookmark-paperclip-set.jpg",
  "laser-cut-coffee-and-book-stack-wooden-keychain": "/products/v5/laser-cut-coffee-and-book-stack-wooden-keychain.jpg",
  "laser-cut-acrylic-monstera-leaf-led-night-lamp": "/products/v5/laser-cut-acrylic-monstera-leaf-led-night-lamp.jpg",
  "laser-engraved-acrylic-starlight-tree-column-lamp": "/products/v5/laser-engraved-acrylic-starlight-tree-column-lamp.jpg",
  "laser-cut-arched-boho-botanical-wooden-wall-art-trio": "/products/v5/laser-cut-arched-boho-botanical-wooden-wall-art-trio.jpg",
  "laser-engraved-house-shaped-wooden-welcome-keychain-pack": "/products/v5/laser-engraved-house-shaped-wooden-welcome-keychain-pack.jpg",
  "laser-cut-wooden-pocket-multi-tool-ruler-keychain": "/products/v5/laser-cut-wooden-pocket-multi-tool-ruler-keychain.jpg",
  "laser-cut-layered-wooden-cover-spiral-journal": "/products/v5/laser-cut-layered-wooden-cover-spiral-journal.jpg",
  "laser-cut-precision-acrylic-chess-set-and-board": "/products/v5/laser-cut-precision-acrylic-chess-set-and-board.jpg",
  "laser-cut-layered-mandala-wooden-napkin-holder-set": "/products/v5/laser-cut-layered-mandala-wooden-napkin-holder-set.jpg",
  "laser-cut-monstera-plant-layered-wooden-desk-sculpture": "/products/v5/laser-cut-monstera-plant-layered-wooden-desk-sculpture.jpg",
  "laser-engraved-clear-acrylic-floral-medallion-keychain": "/products/v5/laser-engraved-clear-acrylic-floral-medallion-keychain.jpg",
  "laser-cut-layered-butterfly-hardwood-cover-notebook": "/products/v5/laser-cut-layered-butterfly-hardwood-cover-notebook.jpg",
  "laser-engraved-personalized-wildflower-acrylic-night-light": "/products/v5/laser-engraved-personalized-wildflower-acrylic-night-light.jpg",
  "cnc-v-carved-solid-walnut-name-plate": "/products/v4/cnc-v-carved-solid-walnut-name-plate.jpg",
  "cnc-relief-carved-wooden-decorative-panel": "/products/v4/cnc-relief-carved-wooden-decorative-panel.jpg",
  "cnc-milled-hardwood-keepsake-box": "/products/v4/cnc-milled-hardwood-keepsake-box.jpg",
  "cnc-machined-6061-aluminium-l-bracket": "/products/v4/cnc-machined-6061-aluminium-l-bracket.jpg",
  "cnc-precision-aluminium-fixture-plate": "/products/v4/cnc-precision-aluminium-fixture-plate.jpg",
  "cnc-machined-high-precision-spur-gear": "/products/v4/cnc-machined-high-precision-spur-gear.jpg",
  "cnc-machined-aluminium-heat-sink": "/products/v4/cnc-machined-aluminium-heat-sink.jpg",
  "cnc-machined-brass-knob-set": "/products/v4/cnc-machined-brass-knob-set.jpg",
  "cnc-precision-aluminium-mounting-block": "/products/v4/cnc-precision-aluminium-mounting-block.jpg",
  "cnc-machined-stainless-steel-coupling": "/products/v4/cnc-machined-stainless-steel-coupling.jpg",
  "cnc-machined-aluminium-motor-mount": "/products/v4/cnc-machined-aluminium-motor-mount.jpg",
  "cnc-machined-precision-bearing-housing": "/products/v4/cnc-machined-precision-bearing-housing.jpg",
  "esp32-dual-core-iot-development-board": "/products/v4/esp32-dual-core-iot-development-board.jpg",
  "37-piece-iot-sensor-module-starter-kit": "/products/v4/37-piece-iot-sensor-module-starter-kit.jpg",
  "double-sided-fr4-prototype-pcb-pack": "/products/v4/double-sided-fr4-prototype-pcb-pack.jpg",
  "arduino-compatible-atmega328p-microcontroller": "/products/v4/arduino-compatible-atmega328p-microcontroller.jpg",
  "i2c-096-inch-oled-display-module": "/products/v4/i2c-096-inch-oled-display-module.jpg",
  "esp32-oled-iot-display-kit": "/products/v4/esp32-oled-iot-display-kit.jpg",
  "arduino-sensor-expansion-shield": "/products/v4/arduino-sensor-expansion-shield.jpg",
  "raspberry-pi-gpio-prototype-board": "/products/v4/raspberry-pi-gpio-prototype-board.jpg",
  "8-channel-relay-module": "/products/v4/8-channel-relay-module.jpg",
  "lora-wireless-communication-module": "/products/v4/lora-wireless-communication-module.jpg",
  "usb-c-power-delivery-development-board": "/products/v4/usb-c-power-delivery-development-board.jpg",
  "4-channel-motor-driver-module": "/products/v4/4-channel-motor-driver-module.jpg",
  "5-inch-fpv-racing-3k-carbon-fiber-drone-frame": "/products/v4/5-inch-fpv-racing-3k-carbon-fiber-drone-frame.jpg",
  "2207-2450kv-high-power-brushless-drone-motor": "/products/v4/2207-2450kv-high-power-brushless-drone-motor.jpg",
  "5-inch-tri-blade-fpv-drone-propellers-pack": "/products/v4/5-inch-tri-blade-fpv-drone-propellers-pack.jpg",
  "30a-4-in-1-blheli-s-electronic-speed-controller": "/products/v4/30a-4-in-1-blheli-s-electronic-speed-controller.jpg",
  "omnidirectional-58ghz-fpv-cloverleaf-antenna": "/products/v4/omnidirectional-58ghz-fpv-cloverleaf-antenna.jpg",
  "fpv-drone-motor-mount-set": "/products/v4/fpv-drone-motor-mount-set.jpg",
  "5-inch-fpv-drone-propeller-guard": "/products/v4/5-inch-fpv-drone-propeller-guard.jpg",
  "carbon-fiber-drone-arm-set": "/products/v4/carbon-fiber-drone-arm-set.jpg",
  "fpv-drone-battery-strap-kit": "/products/v4/fpv-drone-battery-strap-kit.jpg",
  "drone-gps-module": "/products/v4/drone-gps-module.jpg",
  "fpv-camera-mount": "/products/v4/fpv-camera-mount.jpg",
  "brushless-motor-propeller-adapter": "/products/v4/brushless-motor-propeller-adapter.jpg",
  "crystal-clear-cast-acrylic-showcase-cube-box": "/products/v4/crystal-clear-cast-acrylic-showcase-cube-box.jpg",
  "laser-engraved-beveled-acrylic-award-trophy": "/products/v4/laser-engraved-beveled-acrylic-award-trophy.jpg",
  "high-clarity-heavy-duty-acrylic-sneeze-shield": "/products/v4/high-clarity-heavy-duty-acrylic-sneeze-shield.jpg",
  "desktop-acrylic-slanted-brochure-menu-holder": "/products/v4/desktop-acrylic-slanted-brochure-menu-holder.jpg",
  "multi-tiered-clear-acrylic-cosmetic-display-riser": "/products/v4/multi-tiered-clear-acrylic-cosmetic-display-riser.jpg",
  "clear-acrylic-business-card-holder": "/products/v4/clear-acrylic-business-card-holder.jpg",
  "acrylic-qr-code-display-stand": "/products/v4/acrylic-qr-code-display-stand.jpg",
  "acrylic-product-display-box": "/products/v4/acrylic-product-display-box.jpg",
  "acrylic-jewelry-display-stand": "/products/v4/acrylic-jewelry-display-stand.jpg",
  "acrylic-menu-stand": "/products/v4/acrylic-menu-stand.jpg",
  "acrylic-desktop-sign-holder": "/products/v4/acrylic-desktop-sign-holder.jpg",
  "multi-level-acrylic-display-shelf": "/products/v4/multi-level-acrylic-display-shelf.jpg",
  "autonomous-4wd-smart-robotic-stem-starter-kit": "/products/v4/autonomous-4wd-smart-robotic-stem-starter-kit.jpg",
  "educational-electronics-soldering-practice-kit": "/products/v4/educational-electronics-soldering-practice-kit.jpg",
  "diy-portable-bluetooth-stereo-speaker-maker-kit": "/products/v4/diy-portable-bluetooth-stereo-speaker-maker-kit.jpg",
  "miniature-solar-powered-stem-rover-buggy-kit": "/products/v4/miniature-solar-powered-stem-rover-buggy-kit.jpg",
  "smart-weather-station-iot-esp8266-maker-kit": "/products/v4/smart-weather-station-iot-esp8266-maker-kit.jpg",
  "diy-arduino-robot-car-kit": "/products/v4/diy-arduino-robot-car-kit.jpg",
  "diy-mini-weather-station-kit": "/products/v4/diy-mini-weather-station-kit.jpg",
  "diy-led-matrix-display-kit": "/products/v4/diy-led-matrix-display-kit.jpg",
  "diy-smart-plant-monitoring-kit": "/products/v4/diy-smart-plant-monitoring-kit.jpg",
  "diy-line-following-robot-kit": "/products/v4/diy-line-following-robot-kit.jpg",
  "diy-solar-tracking-kit": "/products/v4/diy-solar-tracking-kit.jpg",
  "diy-bluetooth-home-automation-kit": "/products/v4/diy-bluetooth-home-automation-kit.jpg",
};

export function productImage(imageKey: string | undefined | null, name?: string | null): string {
  if (!imageKey) return "/products/v5/3d-printed-winged-mythical-dragon-sculpture.jpg";
  if (imageKey.startsWith("http://") || imageKey.startsWith("https://") || imageKey.startsWith("/products/")) {
    return imageKey;
  }
  if (EXACT_SLUG_IMAGE_MAP[imageKey]) {
    return EXACT_SLUG_IMAGE_MAP[imageKey];
  }
  return `/products/v5/${imageKey}.jpg`;
}

export interface ProductViewAngle {
  id: string;
  label: string;
  badgeTitle: string;
  angle: string;
  src: string;
  stageStyle: string;
  thumbStyle: string;
  viewType: "front" | "isometric" | "closeup" | "cad";
}

export function productViewsFor(
  keyOrSlug: string | null | undefined,
  name?: string | null,
): ProductViewAngle[] {
  const main = productImage(keyOrSlug, name);
  return [
    {
      id: "view-front",
      label: "Front View",
      badgeTitle: "STUDIO FRONT VIEW",
      angle: "0° Elevation",
      src: main,
      stageStyle: "scale-100 rotate-0 brightness-100 contrast-100",
      thumbStyle: "scale-100 rotate-0",
      viewType: "front",
    },
    {
      id: "view-iso",
      label: "3D Isometric",
      badgeTitle: "3D ISOMETRIC PROFILE",
      angle: "45° Oblique Angle",
      src: main,
      stageStyle: "scale-105 -rotate-2 drop-shadow-md",
      thumbStyle: "scale-105 -rotate-2",
      viewType: "isometric",
    },
    {
      id: "view-detail",
      label: "Macro Detail",
      badgeTitle: "ZOOMED DETAIL VIEW",
      angle: "Material Texture",
      src: main,
      stageStyle: "scale-125 origin-center contrast-105 saturate-110",
      thumbStyle: "scale-125 origin-center",
      viewType: "closeup",
    },
    {
      id: "view-cad",
      label: "Engineering View",
      badgeTitle: "CAD ORTHOGRAPHIC",
      angle: "Technical Layout",
      src: main,
      stageStyle: "scale-100 contrast-125 brightness-95",
      thumbStyle: "scale-100 contrast-125",
      viewType: "cad",
    },
  ];
}
